name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# cancel previous tests if new commit is pushed to PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
  
jobs:
  build:

    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      checks: write
      
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        java-package: jdk
        cache: gradle
        
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2.4.2

    - name: Run tests with Gradle
      uses: gradle/gradle-build-action@v2.4.2
      with:
        # build includes tests
        arguments: |
          build
          --console=plain
          --parallel
          -Dorg.gradle.parallel.intra=true

    - name: Tests Report
      uses: dorny/test-reporter@v1
      if: success() || failure()                    # run this step even if previous step failed
      with:
          name: Test Results                        # Name of the check run which will be created
          path: '**/build/test-results/test/*.xml'  # Path to test results
          reporter: java-junit                      # Format of test results
          list-suites: 'failed'                     # Limits which test suites are listed: (*all/failed) *default
          list-tests: 'failed'                      # Limits which test cases are listed: (*all/failed/none) *default
          
