name: Publish on Tag

on:
  push:
    tags:
      - 'v*'  # Match tags starting with 'v'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 23

      - name: Extract version from tag
        id: get_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build and publish to GitHub Packages
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ env.VERSION }}

#      - name: Build and publish to Maven Central
#        run: ./gradlew publishAndReleaseToMavenCentral
#        env:
#          VERSION: ${{ env.VERSION }}
#          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.SONATYPE_USERNAME }}
#          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.SONATYPE_PASSWORD }}
#          ORG_GRADLE_PROJECT_signingInMemoryKey: exported_ascii_armored_key
#          ORG_GRADLE_PROJECT_signingInMemoryKeyId: 12345678
#          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: some_password